name: musicly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg:
  flutter_bloc:
  hydrated_bloc:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
   - assets/images/
   - assets/fonts/
   - assets/vectors/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Satoshi
     fonts:
       - asset: assets/fonts/Satoshi-Black.ttf
         weight: 900
       - asset: assets/fonts/Satoshi-Bold.ttf
         weight: 600
       - asset: assets/fonts/Satoshi-Light.ttf
         weight: 500
       - asset: assets/fonts/Satoshi-Medium.ttf
         weight: 400
       - asset: assets/fonts/Satoshi-Regular.ttf
         weight: 300


